spring.application.name=book-service
server.port=8081

spring.data.mongodb.uri=${MONGO_URI:mongodb://localhost:27017/chapterone_books}

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

logging.level.com.chapterone=DEBUG
