spring.application.name=user-service
server.port=8082

spring.data.mongodb.uri=${MONGO_URI:mongodb://localhost:27017/chapterone_users}

jwt.secret=${JWT_SECRET:chapterone-super-secret-key-must-be-at-least-256-bits-long}
borrow.service.url=${BORROW_SERVICE_URL:http://localhost:8083}
jwt.expiration=86400000

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

logging.level.com.chapterone=DEBUG
